### ISSUE TITLE
Enforce Conventional Commits are used when contributing to the repo

### ISSUE THREAD

**Issue by n8ebel** [goobar-dev/goobar-url-shortener#3]
https://www.conventionalcommits.org/en/v1.0.0/

## Acceptance Criteria
- [ ] When contributing to the project, a pre-commit hook should automatically run and ensure that the commit history matches the conventional commit spec

## Implementation Plan
- [ ] Integrate Gradle plugin for defining conventional commit types
- [ ] Define any custom types that are desired for the project
